version: "3.3"
services:
  postgres:
    image: postgis/postgis:latest
    environment:
      POSTGRES_USER: oneawstogo
      POSTGRES_PASSWORD: oneawstogo
      POSTGRES_DB: oneawstogo
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  data:
